### ISSUE TITLE
Clean up and finalize main README

### ISSUE THREAD

**Issue by mkcomer** [microsoft/ccf-app-samples#148]
Clean up & Update demo recon main README

Some thoughts...
- [ ] Clean up context section
- [x] Architecture link does not work...do we want to add a diagram or visual here? #144 
- [x] update repo structure to reflect latest structure #144
- [ ] Add to getting started section - a Developer looking at this folder FROM SCRATCH (How to build, test, etc) across `Running on enclave, running on docker, running on mCCF` 
- [x] Add a `run demo` section....and point to demo-guidance.md doc #144 

Anything else? 

# Acceptance Critera
1. Update README. Some suggestions above, but open to your own interpretation
