### ISSUE TITLE
Make typescript e2e testing flows work with wrapper scripts

### ISSUE THREAD

**Issue by julioalex-rezende** [microsoft/ccf-app-samples#209]
- [x] Change e2e typescript testing flow to be called from wrapper scripts (`test_sandbox.sh` , `test_docker.sh` , `test_mccf.sh` ) #186 
- [x] provide the same checks currently tested in `test.sh` script #212 
- [x] CI/CD #219 
- [x] Convert JSON/CSV to object for typescript tests #186
