### ISSUE TITLE
Improve typescript testing with make and single configuration

### ISSUE THREAD

**Issue by julioalex-rezende** [microsoft/ccf-app-samples#220]
After input from Amaury's team, if they would like us to merge/leverage typescript testing in the sample, we have identified two follow on tasks.

- [x] Move typescript testing to make-e2e-test (this may include refactoring some scripts to start, stop host and governance. #186
- [x] Consolidate to 1 configuration for app and test have same package.json #224 
- [x] (Stretch) Enable Interactive mode #225
